<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Str;

class CreateLinkRequest extends FormRequest
{
    public function prepareForValidation()
    {
        $url = $this->get('url');

        if (! Str::startsWith($url, ['https://', 'http://'])) {
            $this->merge(['url' => "https://{$url}"]);
        }
    }

    public function rules()
    {
        return [
            'title' => 'required|max:255',
            'url' => 'required|url|unique:links',
            'text' => '',
        ];
    }

    public function passedValidation()
    {
    }

    public function all($keys = null)
    {
        $all = parent::all();

        $all['url'] = strtoupper($all['url']);

        return $all; // TODO: Change the autogenerated stub
    }
}
